


TRANG_THAI_THE

Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (121,'NHAN TAI TTT',' ','2023-01-14','2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (81,'THE DA SX','Thẻ đã sản xuất','2023-01-14','2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (141,'THE QUA THOI HAN','Những thẻ đã vượt quá thời hạn kể từ ngày phát hành','2023-01-14','2023-01-14','quan','quan','1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (2,'GUI TSC','Thẻ sinh viên Chi nhánh đã gửi đủ thông tin để TTT cá thể hóa.','2023-01-14','2023-01-14',null,null,'0');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (3,'THE SV DA SX','Các thẻ sinh viên Chi nhánh gửi TSC đã được cá thể hóa thành công chờ chuyển phát.',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (4,'GUI TSC LOI','Các thẻ sinh viên Chi nhánh đã gửi TSC bị trả lại do lỗi 2',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (5,'THE SAI','Thẻ không dập do: sai tên, EMV, thông tin không khớp…',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (6,'CPN TOI TAY KH','Thẻ gửi trực tiếp tới địa chỉ khách hàng đăng ký',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (7,'GUI CPN','Thẻ gửi chuyển phát tới Chi nhánh',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (8,'HOAN CPN','Thẻ gửi trực tiếp tới địa chỉ khác hàng không thành công được hoàn gửi về CNPHT. Chỉ áp dụng cho các thẻ có trạng thái CPN TOI TAY KH',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (9,'NHAN TAI TTT','Thẻ Chi nhánh đăng ký nhận tại TTT',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (10,'CN DA NHAN TAI TTT','Thẻ Chi nhánh đã nhận tại TTT',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (11,'CN DA NHAN','Thẻ Chi nhánh đã nhận từ đơn vị CPN',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (12,'CHO TRA THE KH','Thẻ giao cho bộ phận QHKH đi trả thẻ trực tiếp',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (13,'KH DA NHAN','Thẻ Chi nhánh đã bàn giao cho KH',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (226,'GUI CNP','Gửi thẻ tới chi nhánh','2023-01-14','2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (1,'THE SV CHO XLY','Thẻ sinh viên đang chờ xử lý','2023-01-14',t'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (201,'TRẢ THẺ CHO KHÁCH HÀNG','trathe',null,'2023-01-14',null,null,'1');
Insert into TRANG_THAI_THE (ID,GIA_TRI,MOTA,NGAY_CAPNHAT,NGAY_TAO,NGUOI_CAPNHAT,NGUOI_TAO,TRANG_THAI) values (227,'THE LOI','Thẻ lỗi',null,'2023-01-14',null,null,'0');



Create table DM_LOAI_THE(ID int, 
	NGAY_CAP_NHAT DATE, 
	NGAY_TAO DATE, 
	NGUOI_CAP_NHAT NVARCHAR(255), 
	NGUOI_TAO NVARCHAR(255), 
	TEN_THE NVARCHAR(255), 
	TRANG_THAI NVARCHAR(255)
   )


Insert into DM_LOAI_THE (ID,NGAY_CAP_NHAT,NGAY_TAO,NGUOI_CAP_NHAT,NGUOI_TAO,TEN_THE,TRANG_THAI) values (1,'2023-02-14','2023-02-14',null,'truongtn','Th? qu?c t?','1');
Insert into DM_LOAI_THE (ID,NGAY_CAP_NHAT,NGAY_TAO,NGUOI_CAP_NHAT,NGUOI_TAO,TEN_THE,TRANG_THAI) values (2,null,'2023-02-14',null,'truongtn','Th? sinh viên','1');
Insert into DM_LOAI_THE (ID,NGAY_CAP_NHAT,NGAY_TAO,NGUOI_CAP_NHAT,NGUOI_TAO,TEN_THE,TRANG_THAI) values (3,null,'2023-02-14',null,'truongtn','Th? ghi n? n?i ??a','1');
Insert into DM_LOAI_THE (ID,NGAY_CAP_NHAT,NGAY_TAO,NGUOI_CAP_NHAT,NGUOI_TAO,TEN_THE,TRANG_THAI) values (4,'2023-02-14','2023-02-14',null,'truongtn','Th? Prepaid','1');


  CREATE TABLE DM_DVCP 
   (	ID INT, 
	TEN NVARCHAR(1), 
	DIACHI NVARCHAR(3), 
	TRANG_THAI NVARCHAR(1) DEFAULT 1, 
	NGAY_TAO DATE DEFAULT getDate(), 
	NGUOI_TAO NVARCHAR(1), 
	NGAY_CAPNHAT DATE, 
	NGUOI_CAPNHAT NVARCHAR(1)
   )

   Insert into DM_DVCP (ID,TEN,DIACHI,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (3,'GIAO HANG TIET KIEM','ghtk.vn','1','2023-02-03','Quan','2023-02-03','Quan');
Insert into DM_DVCP (ID,TEN,DIACHI,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (1,'Viettel','https://mail.bidv.com.vn/owa','1','2023-02-03','Tô Nam Tr??ng','2023-02-03','Tô Nam Tr??ng');
Insert into DM_DVCP (ID,TEN,DIACHI,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (2,'Vnpost','https://vnexpress.net','1','2023-02-03','Tô Nam Tr??ng','2023-02-03','Tô Nam Tr??ng');
Insert into DM_DVCP (ID,TEN,DIACHI,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (3,'DLL','https://vnexpress.net','1','2023-02-03','Tô Nam Tr??ng','2023-02-03','Tô Nam Tr??ng');


  CREATE TABLE BRANCHES 
   (	BRANCH_ID NVARCHAR(5), 
	BRANCH_NM NVARCHAR(64), 
	BRANCH_NV NVARCHAR(64), 
	REGION_ID NVARCHAR(5), 
	STATE_ID NVARCHAR(7), 
	ADDR1 NVARCHAR(64), 
	ADDR2 NVARCHAR(64), 
	MAIN_ID NVARCHAR(5)
   )


Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('558','NHTMCP DT&PTVN-CN QUY NHON','NHTMCP DT&PTVN-CN QUY NHON','990','VNBD','SO 155-157, LE HONG PHONG','P TRAN PHU TP QUY NHON','558');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('512','NHTMCP DT&PTVN-CN PHU DIEN','NHTMCP DT&PTVN-CN PHU DIEN','990','VNNA','KHOI 4','TT DIEN CHAU H DIEN CHAU','512');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('446','NHTMCP DT&PTVN-CN MONG CAI-PGD TRA CO','NHTMCP DT&PTVN-CN MONG CAI-PGD TRA CO','990','VNQN','61B LY TU TRONG P.HOA LAC','TP.MONG CAI-QUANG NINH','444');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('371','NHTMCP DT&PTVN-CN YEN BAI','NHTMCP DT&PTVN-CN YEN BAI','990','VNYB','TO 48','P MINH TAN TP YEN BAI','371');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('216','NHTMCP DT&PTVN-CN DONG DA','NHTMCP DT&PTVN-CN DONG DA','990','VNHN','SO 71 NGUYEN CHI THANH','P LANG HA Q DONG DA','216');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('656','NHTMCP DT&PTVN-CN DI AN-BINH DUONG','NHTMCP DT&PTVN-CN DI AN-BINH DUONG','990','VNBI','SO 16 DUONG DT 743, KCN SONG THAN II','P DI AN TX DI AN','656');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('561','NHTMCP DT&PTVN-CN DA NANG','NHTMCP DT&PTVN-CN DA NANG','990','VNDN','90 NGUYEN CHI THANH','P HAI CHAU I Q HAI CHAU','561');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('522','NHTMCP DT&PTVN-CN NAM HA TINH','NHTMCP DT&PTVN-CN NAM HA TINH','990','VNHI','VP CHO THUE KS HAI THUY,','LIEN PHU (KCN), P KY LIEN TX KY ANH','522');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('450','NHTMCP DT&PTVN-CN HA DONG','NHTMCP DT&PTVN-CN HA DONG','990','VNHN','197 QUANG TRUNG','P QUANG TRUNG Q HA DONG','450');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('502','NHTMCP DT&PTVN-CN LAM SON','NHTMCP DT&PTVN-CN LAM SON','990','VNTH','SO 07 DUONG PHAN CHU TRINH','P DIEN BIEN TP THANH HOA','502');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('423','NHTMCP DT&PTVN-CN PHU THO-PGD THUY VAN','NHTMCP DT&PTVN-CN PHU THO-PGD THUY VAN','990','VNPT','KCN THUY VAN, XA THUY VAN','TP.VIET TRI - PHU THO','421');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('551','NHTMCP DT&PTVN-CN THUA THIEN HUE','NHTMCP DT&PTVN-CN THUA THIEN HUE','990','VNTU','SO 41 HUNG VUONG','P PHU HOI TP HUE','551');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('124','NHTMCP DT&PTVN-CN HOAN KIEM','NHTMCP DT&PTVN-CN HOAN KIEM','990','VNHN','SO 194 TRAN QUANG KHAI','P LY THAI TO Q HOAN KIEM','124');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('540','NHTMCP DT&PTVN-CN QUANG TRI','NHTMCP DT&PTVN-CN QUANG TRI','990','VNQT','24 HUNG VUONG','PHUONG 1 TP DONG HA','540');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('633','NHTMCP DT&PTVN-CN BUON HO','NHTMCP DT&PTVN-CN BUON HO','990','VNDL','476 HUNG VUONG','P AN BINH TX BUON HO','633');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('501','NHTMCP DT&PTVN-CN THANH HOA','NHTMCP DT&PTVN-CN THANH HOA','990','VNTH','SO 26 DAI LO LE LOI','P DIEN BIEN TP THANH HOA','501');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('346','NHTMCP DT&PTVN-CN HA GIANG-PGD BAC QUANG','NHTMCP DT&PTVN-CN HA GIANG-PGD BAC QUANG','990','VNHG','TO 3, KHU PHO QUANG VINH, TT VIET QUANG','H.BAC QUANG - HA GIANG','345');
Insert into BRANCHES (BRANCH_ID,BRANCH_NM,BRANCH_NV,REGION_ID,STATE_ID,ADDR1,ADDR2,MAIN_ID) values ('289','NHTMCP DT&PTVN-CN NGOC KHANH','NHTMCP DT&PTVN-CN NGOC KHANH','990','VNHN','SO 27 HUYNH THUC KHANG','P LANG HA Q DONG DA','289');

CREATE TABLE DM_SAN_PHAM (
	ID INT, 
	TEN_SAN_PHAM NVARCHAR(30), 
	NGUOI_TAO NVARCHAR(50), 
	NGAY_TAO DATE, 
	NGUOI_CAPNHAT NVARCHAR(50), 
	NGAY_CAPNHAT DATE, 
	MA_SAN_PHAM NVARCHAR(200)
	); 

Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (1,'SANPHAM1','Hung','2023-03-02','Hung','2023-03-02','SP01');
Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (2,'SANPHAM1','Hung','2023-03-02','Hung','2023-03-02','SP02');
Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (3,'SANPHAM3','Hung','2023-03-02','Hung','2023-03-02','SP03');
Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (4,'SANPHAM4','Hung','2023-03-02','Hung','2023-03-02','SP04');
Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (5,'SANPHAM5','Hung','2023-03-02','Hung','2023-03-02','SP05');
Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (6,'SANG','Hung','2023-03-02',null,'2023-03-02','B8');
Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (7,'D2','Hung',null,null,null,'D2');
Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (8,'I0','Hung',null,null,null,'I0');
Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (9,'B7','Hung',null,null,null,'B7');
Insert into DM_SAN_PHAM (ID,TEN_SAN_PHAM,NGUOI_TAO,NGAY_TAO,NGUOI_CAPNHAT,NGAY_CAPNHAT,MA_SAN_PHAM) values (10,'B9 vip','Hung',null,null,null,'B9');


CREATE TABLE DON_VI (
	MADONVI NVARCHAR(20), 
	TENDONVI NVARCHAR(200), 
	MADONVICHA NVARCHAR(20), 
	MABDS NVARCHAR(10), 
	MACRA NVARCHAR(20), 
	LATESTUPD DATE, 
	BRNLEVEL NVARCHAR(10), 
	MAKV INT, 
	MABDSCHA NVARCHAR(10), 
	EMAILOU NVARCHAR(500), 
	TENDAYDU NNVARCHAR(300), 
	TENVIETTAT NNVARCHAR(100), 
	TRANGTHAI INT, 
	EMAILADDR NNVARCHAR(100), 
	MASOTHUE NVARCHAR(30), 
	HRAREA NVARCHAR(50), 
	MALOAIHINH NVARCHAR(20)
	) ;
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV621D103',N'P. QL và DV kho quỹ',N'BIDV621D1',N'621',N'465',N'2020-0202',null,4,N'621',N'OU=GiaLai-Pleiku',N'Phòng Quản lý và dịch vụ kho quỹ',N'P. QL và D',0,null,null,N'TN',N'009');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV443A503',N'PGD Minh Thành',N'BIDV443A5',N'443',N'152',N'2020-0202',N'PH',3,N'443',N'OU=TayNamQninh',N'Phòng Giao Dịch Minh Thành',N'P. Giao Dị',1,null,null,N'DLPB',N'010');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV6255505',N'Phòng Kế hoạch - Tài chính',N'BIDV62555',N'625',N'521',N'2020-0202',N'PH',4,N'625',N'OU=KonTum',null,null,1,null,null,null,N'009');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV110B1',N'KHỐI NGÂN HÀNG BÁN LẺ',N'BIDV110',N'990',N'1',N'2020-0202',N'HO',null,N'990',null,null,null,1,null,null,null,N'99');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV411A301',N'P. Quản trị tín dụng',N'BIDV411A3',N'411',N'446',N'2020-0202',null,3,N'411',N'OU=SonLa',N'Phòng Quản trị tín dụng',N'P. Quản tr',1,null,null,N'MNPB',N'009');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV789A503',N'PGD Vũ Trọng Phụng',N'BIDV789A5',N'268',N'154',N'2020-0202',N'PH',3,N'268',N'OU=HaDong',N'Phòng Giao dịch Vũ Trọng Phụng',N'P. Giao dị',1,null,null,N'DBHN',N'009');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV099',N'BẮC HƯNG YÊN',N'BIDV',N'466',N'000',N'2020-0202',N'CN',3,N'466',N'OU=BacHungYen',N'BẮC HƯNG YÊN',N'BẮC HƯNG Y',1,N'bachungyen@bidv.com.vn',null,N'DLPB',N'002');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV3753404',N'Phòng Khách hàng cá nhân (TA2)',N'BIDV37534',N'375',N'121',N'2020-0202',N'PH',3,N'375',N'OU=LaoCai',null,null,1,null,null,null,N'009');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV633A2',N'Khối Quản lý Rủi ro',N'BIDV633',N'633',N'000',N'2020-0202',null,4,N'633',N' ',N'Khối Quản lý Rủi ro',N'Khối Quản',1,null,null,N'TN',N'021');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV4713402',N'P. Giao dịch khách hàng',N'BIDV47134',N'471',N'440',N'2020-0202',null,3,N'471',N'OU=ThaiBinh',N'Phòng Giao dịch khách hàng',N'P. Giao dị',1,null,null,N'DBSH',N'009');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV13101',N'BAN ĐIỀU HÀNH',N'BIDV131',N'131',N'740',N'2020-0202',null,5,N'131',N'OU=VAN PHONG 2',N'BAN ĐIỀU HÀNH',N'BAN ĐIỀU H',1,null,null,N'TPHCM',N'019');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV6722401',N'Phòng Khách hàng doanh nghiệp',N'BIDV67224',N'672',N'021',N'2020-0202',N'PH',5,N'672',N'OU=DongNai-Longbinhtan',null,null,1,null,null,null,N'009');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV6860604',N'PGD Thạnh Hóa',N'BIDV68606',N'686',N'153',N'2020-0202',N'PH',5,N'686',N'OU=MocHoa',null,null,1,null,null,null,N'010');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV10001',N'Ban Giám đốc',N'BIDV100',N'72',N'770',N'2020-0202',null,3,N'072',N'OU=TRUNG TAM DAO TAO',N'Ban Giám đốc',N'BAN GĐ',1,null,null,N'DBHN',N'019');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV6860601',N'PGD Vĩnh Hưng',N'BIDV68606',N'686',N'150',N'2020-0202',N'PH',5,N'686',N'OU=MocHoa',null,null,1,null,null,null,N'010');
Insert into DON_VI (MADONVI,TENDONVI,MADONVICHA,MABDS,MACRA,LATESTUPD,BRNLEVEL,MAKV,MABDSCHA,EMAILOU,TENDAYDU,TENVIETTAT,TRANGTHAI,EMAILADDR,MASOTHUE,HRAREA,MALOAIHINH) values ('BIDV139A446',N'P. QUẢN TRỊ TÍN DỤNG',N'BIDV139A4',N'139',N'446',N'2020-0202',null,5,N'139',N'OU=BinhTaySaiGon',N'PHÒNG QUẢN TRỊ TÍN DỤNG',N'P. QUẢN TR',1,null,null,N'TPHCM',N'009');

CREATE TABLE CTH_MTK (
	ID INT, 
	BDS VARCHAR(20), 
	TEN_TRUONG VARCHAR(300), 
	NGAY_KBTK DATE, 
	MA_TK VARCHAR(100), 
	TRANG_THAI VARCHAR(1) DEFAULT 1, 
	NGAY_TAO DATE DEFAULT getDate(), 
	NGUOI_TAO VARCHAR(20), 
	NGAY_CAPNHAT DATE, 
	NGUOI_CAPNHAT VARCHAR(20)) ;

Insert into CTH_MTK (ID,BDS,TEN_TRUONG,NGAY_KBTK,MA_TK,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (1,'122','HVNN',to_date('06/10/2022 12:00:00 AM','MM/DD/YYYY hh:mi:ss AM'),'122HVNN10062022','1',to_date('12/27/2022 12:00:00 AM','MM/DD/YYYY hh:mi:ss AM'),'truongtn',null,null);
Insert into CTH_MTK (ID,BDS,TEN_TRUONG,NGAY_KBTK,MA_TK,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (2,'121','PTIT',to_date('06/10/2022 12:00:00 AM','MM/DD/YYYY hh:mi:ss AM'),'121PTIT10062022','0',to_date('12/27/2022 12:00:00 AM','MM/DD/YYYY hh:mi:ss AM'),'truongtn',null,null);
Insert into CTH_MTK (ID,BDS,TEN_TRUONG,NGAY_KBTK,MA_TK,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (3,'125','HVTL',to_date('01/01/1970 12:00:00 AM','MM/DD/YYYY hh:mi:ss AM'),'125HVTL1711970','1',to_date('11/10/2022 05:07:38 PM','MM/DD/YYYY hh:mi:ss AM'),'truongtn',null,null);
Insert into CTH_MTK (ID,BDS,TEN_TRUONG,NGAY_KBTK,MA_TK,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (-22,'130','RMIT',to_date('09/18/2022 12:00:00 AM','MM/DD/YYYY hh:mi:ss AM'),'130RMIT10122021','1',to_date('09/29/2022 05:14:26 PM','MM/DD/YYYY hh:mi:ss AM'),'truongtn',null,null);
Insert into CTH_MTK (ID,BDS,TEN_TRUONG,NGAY_KBTK,MA_TK,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (121,'121','RMIT',to_date('10/20/2022 12:00:00 AM','MM/DD/YYYY hh:mi:ss AM'),'121RMIT20102022','1',to_date('11/10/2022 05:46:07 PM','MM/DD/YYYY hh:mi:ss AM'),'truongtn',null,null);
Insert into CTH_MTK (ID,BDS,TEN_TRUONG,NGAY_KBTK,MA_TK,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (161,'121','XXXXX',to_date('10/13/2022 12:00:00 AM','MM/DD/YYYY hh:mi:ss AM'),'121XXXXX13102022','1',to_date('11/10/2022 05:43:43 PM','MM/DD/YYYY hh:mi:ss AM'),null,null,null);
Insert into CTH_MTK (ID,BDS,TEN_TRUONG,NGAY_KBTK,MA_TK,TRANG_THAI,NGAY_TAO,NGUOI_TAO,NGAY_CAPNHAT,NGUOI_CAPNHAT) values (83,'502','sssssssss',to_date('03/02/0333 11:53:30 PM','MM/DD/YYYY hh:mi:ss AM'),'502sssssssss33333','1',to_date('10/04/2022 03:13:42 PM','MM/DD/YYYY hh:mi:ss AM'),'truongtn',null,null);




